### ISSUE TITLE
On mobile phones, the position of the input box is not fixed at the bottom.

### ISSUE THREAD

**Issue by ninvfeng** [anse-app/anse#10]
### What operating system are you using?

android

### What browser are you using?

chrome and wechat

### Describe the bug

On mobile phones, the position of the input box is not fixed at the bottom.
![telegram-cloud-photo-size-4-5958620615114079067-y](https://user-images.githubusercontent.com/6409949/236591945-087ac780-ea2b-4f2c-8867-889d56749afa.jpg)

### What provider are you using?

None

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by ninvfeng** [comment]
pull request https://github.com/anse-app/anse/pull/11

**Comment by yzh990918** [comment]
Thanks!
