### ISSUE TITLE
来催更啦，chatGPT4-turbo模型，需要加入了

### ISSUE THREAD

**Issue by nsnsqk** [anse-app/anse#114]
### Describe the feature

chatGPT4-turbo模型，需要加入了

### Participation

- [ ] I am willing to submit a pull request for this feature.

**Comment by ddiu8081** [comment]
"GPT-4 Turbo is available for all paying developers to try by passing `gpt-4-1106-preview` in the API and we plan to release the stable production-ready model in the coming weeks."

According to https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo, `gpt-4-1106-preview` is the new GPT-4 Turbo model. We already have `gpt-4-1106-preview` option, you can use it.

**Comment by nsnsqk** [comment]
> "GPT-4 Turbo is available for all paying developers to try by passing `gpt-4-1106-preview` in the API and we plan to release the stable production-ready model in the coming weeks."
> 
> According to https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo, `gpt-4-1106-preview` is the new GPT-4 Turbo model. We already have `gpt-4-1106-preview` option, you can use it.

nice，thank you
