### ISSUE TITLE
How to report web vulnerability ?

### ISSUE THREAD

**Issue by guillaC** [anse-app/anse#149]
### What operating system are you using?

Windows

### What browser are you using?

Brave

### Describe the bug

Hello, 

how can I report a web vulnerability ?
Should I contact a specific email address or can I post it directly here ?

### What provider are you using?

None

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ddiu8081** [comment]
Hi guillaC,
Now you can privately reporting a security vulnerability, click "Security" tab and "Report a vulnerability" to open the advisory form, Thanks!

**Comment by guillaC** [comment]
> Hi guillaC, Now you can privately reporting a security vulnerability, click "Security" tab and "Report a vulnerability" to open the advisory form, Thanks!

done ;). Have a good day!
