### ISSUE TITLE
Maximum token not update with model

### ISSUE THREAD

**Issue by jwjoel** [anse-app/anse#32]
### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the bug

The token count does not change with the model's modification. For example, for GPT-3.5, the maximum token count is 4096, while for GPT-4, it is 8192. However, in anse, the token count remains consistent across all models.

### What provider are you using?

OpenAI

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by yzh990918** [comment]
Thanks for your reply, Do you try to change the Max_Token settings？
![image](https://github.com/anse-app/anse/assets/46418596/7310209d-0013-42f8-b6c6-b81769e9674c)

**Comment by jwjoel** [comment]
Basically yes! It's a dynamic process. For instance - when users select GPT-4, the Max Tokens will automatically increase to 8192, while selecting GPT-3.5 will adjust the Max Tokens to 4096. And also, for GPT-4-32k, it should be 32000.

**Comment by yzh990918** [comment]
> 

OK, it will be resolved as soon as possible.

**Comment by yzh990918** [comment]
> Basically yes! It's a dynamic process. For instance - when users select GPT-4, the Max Tokens will automatically increase to 8192, while selecting GPT-3.5 will adjust the Max Tokens to 4096. And also, for GPT-4-32k, it should be 32000.

OK, it will be resolved as soon as possible.

**Comment by yzh990918** [comment]
> Basically yes! It's a dynamic process. For instance - when users select GPT-4, the Max Tokens will automatically increase to 8192, while selecting GPT-3.5 will adjust the Max Tokens to 4096. And also, for GPT-4-32k, it should be 32000.

We adjusted the restrictions a bit,  you can try to modify the configuration, but we don't plan to make it dynamic.
