### ISSUE TITLE
Chat content rendering exception.

### ISSUE THREAD

**Issue by Caojiahao-Coder** [anse-app/anse#47]
### What operating system are you using?

Windows

### What browser are you using?

Chrome

## Sorry the bug #43  isn't fixed in Docker Image (V1.1.5->latest). 

> *Chrome Console has no error output.*

### Input
![1685064613758](https://github.com/anse-app/anse/assets/68038353/b14d9f25-dbf4-41bc-84af-f7b1962d2c4d)
### Output
![1685064621829](https://github.com/anse-app/anse/assets/68038353/0c6c509e-f79e-4273-9b4f-dc25b2b323c5)
### Docker Image
![image](https://github.com/anse-app/anse/assets/68038353/7db317db-9cfd-425f-b239-7f1215f1b889)

### What provider are you using?

OpenAI

### What prompt did you enter?

```
<div>
  Hello World
</div>
Please explain this code snippet.
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ddiu8081** [comment]
We have launched [v1.1.6](https://github.com/anse-app/anse/releases/tag/v1.1.6), try to pull the latest image.

**Comment by Caojiahao-Coder** [comment]
In [v1.1.6](https://github.com/anse-app/anse/releases/tag/v1.1.6), this problem seems to be fixed, thanks!🥳

**Comment by Caojiahao-Coder** [comment]
> We have launched [v1.1.6](https://github.com/anse-app/anse/releases/tag/v1.1.6), try to pull the latest image.

In [v1.1.6](https://github.com/anse-app/anse/releases/tag/v1.1.6), this problem seems to be fixed, thanks!
