### ISSUE TITLE
 provider_error Failed to execute 'fetch' on 'Window': Failed to read the 'headers' property from 'RequestInit': String contains non ISO-8859-1 code point.

### ISSUE THREAD

**Issue by 1592363624** [anse-app/anse#50]
### What operating system are you using?

win11

### What browser are you using?

edge

### Describe the bug

![image](https://github.com/anse-app/anse/assets/50036597/aadd30ac-8dd0-4824-bdba-666dbf8e8ff2)

### What provider are you using?

None

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ddiu8081** [comment]
Do you have an invalid character in OpenAI API Key? e.g. `\n`, space?

**Comment by 1592363624** [comment]
> Is there an invalid character in your OpenAI API Key input box, such as a `\n` or space, or a Chinese character?

确实是APIkey错了
