### ISSUE TITLE
[Feature] Add network search function

### ISSUE THREAD

**Issue by hisune** [anse-app/anse#56]
### Describe the feature

Functions similar to this chrome extension:

https://chrome.google.com/webstore/detail/webchatgpt-chatgpt-with-i/lpfemeioodjbpieminkklglpmhlngfcn

Call duckduckgo or Google's API to search web results for networking

### Participation

- [ ] I am willing to submit a pull request for this feature.

**Comment by yzh990918** [comment]
Thanks. We'll add features like conversation search.
