### ISSUE TITLE
Words breaks at the end of line

### ISSUE THREAD

**Issue by Nikit-Singh** [anse-app/anse#7]
### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the bug

The text in the StreamableText component is currently using the "break-all" class, which results in words being split between lines and can create a poor user experience. To address this issue, the "break-words" class can be used. I have already made the necessary changes on a fork and can create a pull request if necessary.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by ddiu8081** [comment]
pr welcome, thank you!

**Comment by Nikit-Singh** [comment]
Created the [PR here](https://github.com/anse-app/anse/pull/9).
