### ISSUE TITLE
PWA can work on Netlify deploys

### ISSUE THREAD

**Issue by CNSeniorious000** [anse-app/anse#71]
### Describe the feature

By just change the way to inject Service Worker, Anse can deploy on Netlify with PWA enabled. Just like [#419](https://github.com/anse-app/chatgpt-demo/pull/419). May I PR similarly?

### Participation

- [X] I am willing to submit a pull request for this feature.

**Comment by yzh990918** [comment]
Yean, Thanks for your work.

**Comment by CNSeniorious000** [comment]
Implemented in #79 ~
