### ISSUE TITLE
Allow for the configuration of the length of historical messages to circumvent the constraints imposed by the MaxTokens parameter.

### ISSUE THREAD

**Issue by chancelyg** [anse-app/anse#74]
### Describe the feature

![DeepinScreenshot_select-area_20230626143031](https://github.com/anse-app/anse/assets/38032874/a22b1ead-7678-417c-bddf-9c353bfd7331)

Upon observation, I have come to the realization that after a certain duration of usage, it becomes necessary to delete historical messages once they exceed approximately ten in number. Unfortunately, the current configuration does not provide a solution to address this issue adequately.

Would it be possible to introduce a feature that allows for customization of the quantity of historical messages?

### Participation

- [ ] I am willing to submit a pull request for this feature.

**Comment by CNSeniorious000** [comment]
I think we could merge *Single Chat* mode with this feature. Imagine a `max-length` parameter to control the max length of the sliding context window. With `max-length` setting to `1`, this is the *Single Chat* mode with message history.

Furthermore, I think this could be extended to other kinds of message filtering. Such as:

`max-tokens` - The maximum of the tokens count of sliding window of context to pass. Mention that tiktoken now have a [WASM version](https://www.npmjs.com/package/tiktoken) that can be easily [integrated with Astro](https://github.com/anse-app/chatgpt-demo/issues/291).

`min-relevance` - The minimum of similarity between the current message and the foremost message in context to pass. OpenAI's [Embeddings](https://platform.openai.com/docs/guides/embeddings) model is a good choice.
